name: Deploy Application to Live Server

on:
  push:
    branches: ["live"]
  pull_request:
    branches: ["live"]

jobs:
  live-server-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 82.112.235.17
          port: 22
          username: dhaka9356
          password: 7YvmJ71lQm4MlQBe6Wm+
          script: |
            cd /home/dhakapharmacy.com.bd/public_html
            git fetch --all
            git reset --hard origin/live
            php artisan optimize:clear
            php artisan migrate --force
