name: Deploy Application to Staging Server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  sandbox-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: "sandbox.dhakapharmacy.com.bd"
          port: 22
          username: "sandb3927"
          password: "DP@2025EuitSols"
          script: |
            cd /home/sandbox.dhakapharmacy.com.bd/public_html
            git fetch --all
            git reset --hard origin/main
            php artisan optimize:clear
