name: Deploy Application to Staging Server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  sandbox-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{SANDBOX_HOST}}
          port: ${{SANDBOX_PORT}}
          username: ${{SANDBOX_USERNAME}}
          password: ${{SANDBOX_PASSWORD}}
          script: |
            cd /home/sandbox.dhakapharmacy.com.bd/public_html
            git fetch --all
            git reset --hard origin/main
            php artisan optimize:clear
